version: '3.3'

services:

    wordpress:
        image: wordpress
        restart: always
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: secret
            WORDPRESS_DB_NAME: docker_wordpress
          
    mysql:
        image: mysql:latest
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret