apache:
    build: apache-php
    restart: always
    volumes:
        - /var/www:/var/www
    ports:
        - 1337:80
    links:
        - php:php
    environment:
        - VIRTUALHOST=iamdeveloper.io